# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 百度极速版

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 7-23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        BAIDU_COOKIE: ${{ secrets.BAIDU_COOKIE }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/jiuli12/baiduAction.git ~/baiduAction
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.BAIDU_COOKIE
        run: |
          cd ~/baiduAction
          npm install
      - name: '运行 【百度极速版】'
        if: env.BAIDU_COOKIE
        run: |
          cd ~/baiduAction
          node baidu_speed.js
        env:
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
